#!/usr/bin/sh

if [ -z $1 ]
then
	echo "Missing a slug"
	exit 0
fi
slug=$1

fold=$(date +"content/%Y/%m")
mkdir -p $fold
NEWFILE="$fold/$(date +'%d')-${slug}.md"

mv drafts/${slug}.md "$NEWFILE"
perl -ni -e 'print unless $_ eq "Status: draft\n"' "$NEWFILE"

