#!/usr/bin/env python

from __future__ import print_function
import argparse
import os
import sys


template = r'''
Title: {0.title}
Category: {0.category}
Status: draft
'''.strip()


def parse_args(argv):
    parser = argparse.ArgumentParser(description="Create a new draft")
    parser.add_argument('slug', help="The slug to use")
    parser.add_argument('--title', '-t', help="Page title", default="")
    parser.add_argument("--category", "-c", help="Page category", default="")
    parser.add_argument("--tags", nargs="+", default=[], help="Page tags")
    parser.add_argument("--parts", "-p", nargs="+", default=[], help="Page parts")
    return parser.parse_args(argv)


def main(argv):
    argv = argv or sys.argv
    args = parse_args(argv[1:])
    with open(os.path.join("drafts", args.slug + ".md"), 'w') as fi:
        print(template.format(args), file=fi)
        if args.tags:
            print("Tags: {0}".format(",".join(args.tags)), file=fi)
        if args.parts:
            print("Parts: {0}".format(",".join(args.parts)), file=fi)
        print("", file=fi)


if __name__ == '__main__':
    main(sys.argv)

