#!/usr/bin/env python

from __future__ import print_function
import argparse
import os
import os.path as path
import time

parser = argparse.ArgumentParser()
parser.add_argument("slug")
args = parser.parse_args()

fold = time.strftime("content/%Y/%m")
try:
    os.makedirs(fold)
except OSError:
    pass
rawslug = os.path.basename(args.slug)
rawslug = os.path.splitext(rawslug)[0]
newfile = path.join(fold, time.strftime('%d-') + rawslug + ".md")
oldfile = args.slug
if not os.path.isfile(oldfile):
    oldfile = path.join("drafts", args.slug + ".md")

with open(oldfile) as infi:
    with open(newfile, 'w') as outfi:
        for line in (line for line in infi if "Status: draft" not in line):
            print(line, end='', file=outfi)
os.remove(oldfile)
